### ISSUE TITLE
[Feature Request] Config for teleport event listener

### ISSUE THREAD

**Issue by Aho-Senpai** [castcrafter/travel_anchors#21]
Similar to how Ender IO anchor worked, allow the player to use jump to teleport to the anchor they are looking at instead of right-click. 
I find myself teleporting to an anchor i don't want to when I'm trying to open a chest that has an anchor in my line-of-sight further away. 
Having an option to change the teleport behavior to jump instead of right-click would fix that issue in my opinion

**Comment by noeppi-noeppi** [comment]
I'll upload a file today where teleportation has a lower priority than block interactions so you can open chests with the travel staff in your hand. There will also be a client option that disabled elevation and changes jump to teleport to the anchor you're looking at. Because it's a client option you can activate it and also play with others that don't have it activated. However the won't be an option to disable teleportation via right click. But I think this should be okay because block interaction now has a higher priority. If you still feel you need an option to disable teleportation with a right click entirely, feel free to reopen the issue.
